config/routes.rb
Rails.application.routes.draw do
  root to: 'books#top'
  get '/books/about',to: 'books#about', as:'about'
  devise_for :users
  resources :users, only: [:index,:show,:edit,:update]
  resources :books, only: [:edit,:update,:create,:index,:show,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

   validates :title, presence: true, length: {maximum: 50}
   validates :book_caption, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :books, dependent: :destroy
   attachment :user_image

   validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20}
   validates :user_caption, length: {maximum: 50}
  #emailを不要とする
  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters,if: :devise_controller?



	def after_sign_in_path_for(resource)
	    user_path(current_user.id) # マイページへ
	end

	def after_sign_out_path_for(resource)
	    root_path # ログアウト後に遷移するpathを設定
	end

	protected

	def configure_permitted_parameters
	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email,:password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :user_image_id, :user_caption) }

	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!,except: [:top,:about]
	before_action :correct_user, only:[:edit,:update]
	def top
	end

	def about
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			flash[:notice] = "Book was successfully created"
			redirect_to book_path(@book.id)
		 else
			flash[:notice] = "error:字数制限・空白にご注意ください。"
		 	redirect_to user_path(current_user.id)
		end
		# 	render "books/top"
		# end
	end

	def edit
	end

	def update
		@book.user_id = current_user.id
		if @book.update(book_params)
			flash[:notice] = "Book was successfully updated"
			redirect_to book_path(@book)
		else
			flash[:notice] = "error:字数制限・空白にご注意ください。"
			redirect_to edit_book_path(@book)
		end
	end

	def index
		# 本のタイトル・感想一覧用
		@books = Book.all
		# ユーザーの顔写真一覧用
		@users = User.all
		# テンプレ用
		@book = Book.new
	end

	def show
		# テンプレ用
		@book = Book.new
		# ユーザー投稿済みブック一覧詳細用
		@userbook = Book.find(params[:id])
	end

	def destroy
		@book = Book.find(params[:id])
		if @book.destroy
			flash[:notice] = "Book was successfully deleted"
			redirect_to books_path
		else
			redirect_to book_path(@book)
		end
	end
	private

	def correct_user
  		@book = Book.find(params[:id])
  		redirect_to root_path unless @book.user_id == current_user.id
  	end

	def book_params
		params.require(:book).permit(:title,:book_caption)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only:[:edit,:update]
	def index
		# ユーザ一覧表示用
		@users = User.all
		# テンプレnewbook用
		@book = Book.new
	end
	def edit
	end

	def update
		if @user.update(user_params)
			flash[:notice] = "User infomation was successfully updated"
			redirect_to user_path(@user.id)
		else
			flash[:notice] = "error:字数制限・空白にご注意ください。"
			redirect_to edit_user_path(@user)
		end
	end

  def show
  	#テンプレUserinfo用
  	@user = User.find(params[:id])
  	@book = Book.new
  	# 一覧表示用
  	@books = Book.all
  end

  private
  	def correct_user
  		@user = User.find(params[:id])
  		redirect_to root_path unless @user == current_user
  	end

    def user_params
        params.require(:user).permit(:user_image, :name, :user_caption)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-xs-3">
	<h2>User Info</h2>
	<%= attachment_image_tag user, :user_image, :fill,60,60, format:'jpeg',fallback: "no_image.jpg",size:"60x60"%><br><hr>
	<p>名前:<%= user.name %></p><hr>
	<p>自己紹介:<%= user.user_caption %></p><hr>
	<% if user.id == current_user.id%>
		<%= link_to "", edit_user_path(user),class:"btn btn-default btn-block glyphicon glyphicon-cog edit_user_#{user.id}"%>
	<% end %>
	<h2>新規投稿</h2>
	<%= form_for(book) do |f| %>
		<div class="field">
			<%= f.label :タイトル %><br>
			<%= f.text_field :title, class:"col-xs-12 book_title" %>
		</div>
		<div class="field">
			<%= f.label :本文 %><br>
			<%= f.text_area :book_caption, class:"col-xs-12 book_body"%><br>
		</div>
		<%= f.submit "作成", class:"btn btn-primary col-xs-12"%>
	<% end %>
</div>

app/views/books/about.html.erb
<div class="container">
	<div class="row">
		<h1>About is the only word for this page. </h1>
	</div>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <% if flash[:notice] %>
        <%= flash[:notice] %>
      <% end %>
      <h2>投稿内容変更</h2>
      <%= form_for(@book) do |f| %>
        <div class="field row">
          <%= f.label :タイトル %><br>
          <%= f.text_field :title, class:"col-xs-12 book_title"%>
        </div>

        <div class="field row">
          <%= f.label :本文 %><br>
          <%= f.text_area :book_caption,class:"col-xs-12 book_body" %><br>
        </div>
        <p></p>
        <div class="actions row">
          <%= f.submit :変更,class:"btn btn-success col-xs-12 submit"%><br>
        </div>
      <% end %>
      <%= link_to "show",book_path(@book.id),class:"book_#{@book.id}"%>
      <span>|</span>
      <%= link_to "Back",books_path, class:"back"%>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<%=render 'books/list', user: current_user, book: @book;%>
		<div class="col-xs-9">
			<% if flash[:notice] %>
				<p><%= flash[:notice] %></p>
			<% end %>
			<h2>Books</h2>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book|%>
						<tr>
							<td><%= attachment_image_tag book.user, :user_image, :fill,30,30, format:'jpeg',fallback: "no_image.jpg",size:"30x30"%></td>
							<td><%= link_to "#{book.title}",book_path(book.id),class:"book_#{book.id}"%></td>
							<td><%= book.book_caption %></td>
						</tr>
				</tbody>
				<%end%>
			</table>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<%=render 'books/list', user: @userbook.user,
		book: @book %>
		<div class="col-xs-9">
			<% if flash[:notice]%>
				<p><%= flash[:notice] %></p>
			<% end %>
			<h2>Book details</h2>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
				<tr>
					<td><%= attachment_image_tag @userbook.user, :user_image, :fill,30,30, format:'jpeg',fallback: "no_image.jpg",size: "30x30"%><br>
						<%= link_to "#{@userbook.user.name}",user_path(@userbook.user.id),class:"user_#{@userbook.user.id}" %></td>
					<td><%= link_to "#{@userbook.title}",book_path(@userbook.id),class:"book_#{@userbook.id}"%></td>
					<td><%= @userbook.book_caption %></td>
					<%if current_user.id == @userbook.user.id %>
						<td><%= link_to "Edit",edit_book_path(@userbook.id), class:"btn btn-success edit_book_#{@userbook.id}"%></td>
						<td><%= link_to "Delete",book_path(@userbook.id), method: :delete, data: {confirm: '削除してよろしいですか？'} ,class:"btn btn-danger destroy_book_#{@userbook.id}"%></td>
					<% end %>
				</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/books/top.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3"></div>
		<div class="col-xs-6">
			<h2>Welcome to
				<span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers</strong></span>!!
			</h2>
			<p>In
				<span class="glyphicon glyphicon-book" aria-hidden="true">Bookers</span>,<br>
				you can share and exchange your opinions , inpressions , and emotions<br>
				about varioius books!
			</p>
			<%= link_to "Log in", new_user_session_path, class:"btn btn-success btn-block sign_in" %>
			<%= link_to "Sign up", new_user_registration_path, class:"btn btn-primary btn-block sign_up" %>
		</div>
		<div class="col-xs-3"></div>
	</div>
</div>

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
	<h2><%= model.errors.count%>件</h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdvBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar navbar-inverse navbar-fixed">
      <div class="container">
        <div class="navbar-header">
          <span style="font-size:30px; color:#fff;">Booker</span>
        </div>
       <div class="collapse navbar-collapse" id="bookers_header">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="">
              <%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %>
            </li>
            <li class="">
              <%= link_to " Users", users_path, class: "glyphicon glyphicon-user users"%>
            </li>
            <li class="">
              <%= link_to " Books", books_path,class: "glyphicon glyphicon-book books"%>
            </li>
            <li class="">
              <%= link_to " Logout",destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout"%>
          <% else %>
            <li class="">
              <%= link_to " Home", root_path, class: "glyphicon glyphicon-home home" %>
            </li>
            <li class="">
              <%= link_to " About", about_path, class: "glyphicon glyphicon-link about"%>
            </li>
            <li class="">
              <%= link_to " SingUp", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up"%>
            </li>
            <li class="">
              <%= link_to " Login", user_session_path, class: "glyphicon glyphicon-log-in sign_in"%>
            </li>
          <% end %>
        </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
  <h2>プロフィール変更</h2>

  <%= form_for @user, url: user_path(@user.id),method: :patch do |f| %>

    <div class="field">
      <%= f.label :名前 %><br />
      <%= f.text_field :name, autofocus: true, placeholder: "名前",class:"name"%>
    </div>

    <div class="field">
      <%= f.label :プロフィール画像 %><br />
      <%= f.attachment_field :user_image,class:"user_image"%>
    </div>

    <div class="field">
      <%= f.label :自己紹介文_50文字まで%><br />
      <%= f.text_area :user_caption, class:"introduction"%>
    </div>

    <div class="actions">
      <%= f.submit "更新" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<%=render 'books/list', user: current_user,book: @book %>
		<div class="col-xs-9">
			<h2>Users</h2>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user|%>
						<tr>
							<td><%= attachment_image_tag user, :user_image, :fill,30,30, format:'jpeg',fallback: "no_image.jpg",size: "30x30"%><br></td>
							<td><%= user.name %></td>
							<td><%= link_to 'show', user_path(user.id),class:"user_#{user.id}"%></td>
						</tr>
				</tbody>
				<%end%>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<%=render 'books/list', user: @user, book: @book;%>
		<div class="col-xs-9">
			<% if flash[:notice]%>
				<p><%= flash[:notice] %></p>
			<% end %>
			<h2>Books</h2>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% @books.where(:user_id => @user.id).find_each do |book|%>
						<tr>
							<td><%= attachment_image_tag book.user, :user_image, :fill,30,30, format:'jpeg',fallback: "no_image.jpg",size: "30x30" %></td>
							<td><%= link_to "#{book.title}",book_path(book.id), class:"book_#{book.id}"%></td>
							<td><%= book.book_caption %></td>
						</tr>
				</tbody>
				<%end%>
			</table>
		</div>
	</div>
</div>